language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../MultiStack
  - make -j
  - ls
  - ./test/MultiStack_Test
notifications:
  email: false
